# Generated by Django 5.1 on 2024-08-29 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="likes",
        ),
        migrations.AddField(
            model_name="video",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
