# Generated by Django 5.1 on 2024-08-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0002_remove_video_likes_video_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnail/"),
        ),
    ]
