# Generated by Django 5.0.6 on 2024-09-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.IntegerField(default=True),
        ),
    ]
