# Generated by Django 5.1 on 2024-09-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0005_remove_video_likes_video_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="comments",
            field=models.IntegerField(default=0),
        ),
    ]
