# Generated by Django 5.1 on 2024-09-08 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0006_alter_video_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
