# Generated by Django 5.1 on 2024-09-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0007_video_liked_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="likes",
            new_name="like_count",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="liked_by",
            new_name="liked",
        ),
    ]
