# Generated by Django 5.1 on 2024-09-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0008_rename_likes_video_like_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="liked",
            new_name="liked_by",
        ),
        migrations.RemoveField(
            model_name="video",
            name="like_count",
        ),
        migrations.AddField(
            model_name="video",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
